<<<<<<< HEAD
# Generated by Django 5.2.3 on 2026-01-28 17:32

from django.db import migrations, models
=======
from django.db import migrations
>>>>>>> c4aab529800c7f6d987e53657184410f45f54862


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

<<<<<<< HEAD
    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_email', models.EmailField(max_length=254)),
                ('round_id', models.IntegerField(null=True)),
                ('score', models.FloatField(default=0.0)),
                ('total_correct', models.IntegerField(default=0)),
                ('time_taken', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortonymWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('synonyms', models.TextField(help_text='Comma-separated synonyms')),
                ('antonyms', models.TextField(help_text='Comma-separated antonyms')),
            ],
        ),
    ]
=======
    operations = []
>>>>>>> c4aab529800c7f6d987e53657184410f45f54862
